---
title: "TFM_Juanjo"
author: "Marcial"
date: "08/22/2017"
output: html_document
---

First, let's edit rbcl tree

```{r}
library(ape)

rbcltree <- read.nexus("rbcl_raxml_tree.nex") 
plot(rbcltree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
rbcltree$tip.label <- paste("s", rbcltree$tip.label, sep="")
rbcltree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(rbcltree$tip.label,mytiplabels2)]
rbcltree2 <- rbcltree
rbcltree2$tip.label <- names(mytiplabels2)[match(rbcltree$tip.label,mytiplabels2)]
plot(rbcltree2)
write.tree(rbcltree2, file = "edited_rbcl.tree")


```

Now matk tree

```{r}


library(ape)

matktree <- read.nexus("matk_raxml_tree.nex") 
plot(matktree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
matktree$tip.label <- paste("s", matktree$tip.label, sep="")
matktree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(matktree$tip.label,mytiplabels2)]
matktree2 <- matktree
matktree2$tip.label <- names(mytiplabels2)[match(matktree$tip.label,mytiplabels2)]
plot(matktree2)
write.tree(matktree2, file = "edited_matk.tree")
```

ITS
```{r}

library(ape)

ITStree <- read.nexus("ITS_raxml_tree.nex") 
plot(ITStree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
ITStree$tip.label <- paste("s", ITStree$tip.label, sep="")
ITStree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(ITStree$tip.label,mytiplabels2)]
ITStree2 <- ITStree
ITStree2$tip.label <- names(mytiplabels2)[match(ITStree$tip.label,mytiplabels2)]
plot(ITStree2)
write.tree(ITStree2, file = "edited_ITS.tree")
```





First, let's edit rbcl tree

```{r}
library(ape)

rbcltree <- read.nexus("rbcl_raxml_tree.nex") 
plot(rbcltree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
rbcltree$tip.label <- paste("s", rbcltree$tip.label, sep="")
rbcltree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,4],mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(rbcltree$tip.label,mytiplabels2)]
rbcltree2 <- rbcltree
rbcltree2$tip.label <- names(mytiplabels2)[match(rbcltree$tip.label,mytiplabels2)]
plot(rbcltree2)
write.tree(rbcltree2, file = "edited_rbcl2.tree")


```

Now matk tree

```{r}


library(ape)

matktree <- read.nexus("matk_raxml_tree.nex") 
plot(matktree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
matktree$tip.label <- paste("s", matktree$tip.label, sep="")
matktree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,4],mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(matktree$tip.label,mytiplabels2)]
matktree2 <- matktree
matktree2$tip.label <- names(mytiplabels2)[match(matktree$tip.label,mytiplabels2)]
plot(matktree2)
write.tree(matktree2, file = "edited_matk2.tree")
```

ITS
```{r}

library(ape)

ITStree <- read.nexus("ITS_raxml_tree.nex") 
plot(ITStree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
ITStree$tip.label <- paste("s", ITStree$tip.label, sep="")
ITStree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,4],mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(ITStree$tip.label,mytiplabels2)]
ITStree2 <- ITStree
ITStree2$tip.label <- names(mytiplabels2)[match(ITStree$tip.label,mytiplabels2)]
plot(ITStree2)
write.tree(ITStree2, file = "edited_ITS2.tree")
```


all
```{r}

library(ape)

alltree <- read.nexus("all_raxml_tree.nex") 
plot(alltree, cex = 0.5)
mytiplabels <- read.csv("Muestras ordenadas.csv")
mytiplabels <- mytiplabels[1:118,]
mytiplabels
mytiplabels[,4] <- paste("s", mytiplabels[,4], sep="")
mytiplabels
alltree$tip.label <- paste("s", alltree$tip.label, sep="")
alltree$tip.label
mytiplabels2 <- mytiplabels[,4]
names(mytiplabels2) = paste(mytiplabels[,4],mytiplabels[,5],mytiplabels[,6], mytiplabels[,7], sep="_")
mytiplabels2
names(mytiplabels2)[match(alltree$tip.label,mytiplabels2)]
alltree2 <- alltree
alltree2$tip.label <- names(mytiplabels2)[match(alltree$tip.label,mytiplabels2)]
plot(alltree2)
write.tree(alltree2, file = "edited_all2.tree")
```


Phylogenetic diversity analyses
```{r}
#1. LOADING DATA


library(picante)
library(phytools)

mytree<- read.nexus("all_raxml_tree.nex") 
plot(mytree, cex = 0.4)
mytree<-root(mytree, c("43","99"))
plot(mytree, cex = 0.4)

mydata <- read.csv("matriz numerica ANALISIS TFM.csv", header = T, row.names = 1) 
mydata

mytree$tip.label
mytree$tip.label <- paste("s", mytree$tip.label, sep="")
setdiff(colnames(mydata), mytree$tip.label)
setdiff(mytree$tip.label, colnames(mydata))
tipstoremove <- setdiff(mytree$tip.label, colnames(mydata))
mytree <- drop.tip(mytree, tipstoremove)

phy <- mytree
comm <- mydata

comm <- as.matrix(comm)
class(comm)
colnames(comm)
rownames(comm)

#2. visualizing trees and data

prunedphy <- prune.sample(comm, phy)
prunedphy

par(mfrow = c(2, 2))
for (i in row.names(comm))
{
plot(prunedphy, show.tip.label = FALSE, main = i)
tiplabels(tip = which(prunedphy$tip.label %in% names(which(comm[i, ] >
0))), pch = 19, cex = 1)
}

#3. Community phylogenetic structure
#3.1 Phylogenetic diversity
pd.result <- pd(comm, phy, include.root = F)
pd.result
write.table(pd.result, file="pd.result.txt")


#3.2.2  MPD, MNTD, SES MPD and SES MNT D
phydist <- cophenetic(phy)
ses.mpd.result <- ses.mpd(comm, phydist, null.model = "taxa.labels",
abundance.weighted = T, runs = 99)
ses.mpd.result
write.table(ses.mpd.result1000, file="ses.mpd.result.txt")


ses.mntd.result <- ses.mntd(comm, phydist, null.model = "taxa.labels",
abundance.weighted = T, runs = 99)
ses.mntd.result
write.table(ses.mntd.result, file="ses.mntd.result.txt")

#4.3 Phylogenetic beta diversity

comdist.result <- comdist (comm, phydist)
comdist.result
write.table(as.matrix(comdist.result), file="comdist.result.txt")


library(cluster)
comdist.clusters <- hclust(comdist.result)
plot(comdist.clusters)

```

